args <- commandArgs(trailingOnly = TRUE)
a = 0
library(stats)
print(a-1)
simMatr = read.table(args[1],header=T)
library(apcluster)
print(a)
ap2 = as.matrix(simMatr)
print(a+1)
library(methods)
ap = apcluster(ap2)
print(a+2)
print(ap)
